

name: weather-grocery-weaver

on:
  schedule:
    - cron: "0 * * * *"   # every hour

steps:
  - id: fetch_weather
    uses: python:run
    with:
      script: scripts/fetch_weather.py

  - id: load_trends
    uses: python:run
    with:
      script: scripts/fetch_trends.py

  - id: merge
    uses: python:run
    with:
      script: scripts/merge_and_clean.py

  - id: publish_dashboard
    uses: storage:upload
    with:
      source: dashboard/data.json
      target: public/data.json
